#!/bin/bash
#
# diff the files in "output" and "output.ref" for all examples
# 
# only the start time comments in the output files should differ
#
# Niles A. Pierce (11 October 2014)
#

OUT1="output"
OUT2="output.ref-3.2.0e"

printf "\n*********************************************************** \n"
printf   "diff output files for complex-analysis: simple examples     \n"
printf   "*********************************************************** \n"
diff -r ./complex-analysis/simple/$OUT1 ./complex-analysis/simple/$OUT2

printf "\n*********************************************************** \n"
printf   "diff output files for complex-analysis: advanced examples   \n"
printf   "*********************************************************** \n"
diff -r ./complex-analysis/advanced/$OUT1 ./complex-analysis/advanced/$OUT2

printf "\n*********************************************************** \n"
printf   "diff output files for complex-analysis: pseudoknot examples \n"
printf   "*********************************************************** \n"
diff -r ./complex-analysis/pseudoknot/$OUT1 ./complex-analysis/pseudoknot/$OUT2

printf "\n*********************************************************** \n"
printf   "diff output files for complex-design: simple examples       \n"
printf   "*********************************************************** \n"
diff -r ./complex-design/simple/$OUT1 ./complex-design/simple/$OUT2

printf "\n*********************************************************** \n"
printf   "diff output files for complex-design: advanced examples     \n"
printf   "*********************************************************** \n"
diff -r ./complex-design/advanced/$OUT1 ./complex-design/advanced/$OUT2

printf "\n*********************************************************** \n"
printf   "diff output files for tube-analysis: simple examples        \n"
printf   "*********************************************************** \n"
diff -r ./tube-analysis/simple/$OUT1 ./tube-analysis/simple/$OUT2

printf "\n*********************************************************** \n"
printf   "diff output files for tube-analysis: advanced examples      \n"
printf   "*********************************************************** \n"
diff -r ./tube-analysis/advanced/$OUT1 ./tube-analysis/advanced/$OUT2

printf "\n*********************************************************** \n"
printf   "diff output files for tube-design: simple examples          \n"
printf   "*********************************************************** \n"
diff -r ./tube-design/simple/$OUT1 ./tube-design/simple/$OUT2

printf "\n*********************************************************** \n"
printf   "diff output files for tube-design: advanced examples        \n"
printf   "*********************************************************** \n"
diff -r ./tube-design/advanced/$OUT1 ./tube-design/advanced/$OUT2

printf "\n*********************************************************** \n"
printf   "diff output files for multitube-design: simple examples     \n"
printf   "*********************************************************** \n"
diff -r ./multitube-design/simple/$OUT1 ./multitube-design/simple/$OUT2

printf "\n*********************************************************** \n"
printf   "diff output files for multitube-design: advanced examples   \n"
printf   "*********************************************************** \n"
diff -r ./multitube-design/advanced/$OUT1 ./multitube-design/advanced/$OUT2
