.TH CT-ENERGY-DET.PL 1 "February 2008" "UNAFold 3.6" "User Commands"
.SH NAME
ct-energy-det.pl \- compute energy details with ct-energy
.SH SYNOPSIS
.B ct-energy-det.pl
.RI [ OPTION ]...
.SH DESCRIPTION
\fBct-energy-det.pl\fR converts the verbose output of \fBct-energy\fR to energy details in plain text or HTML.  Input should generally be piped from a call to "ct-energy -v".
.SH OPTIONS
.TP
.BR -m ", " --mode =text|html
prints output in plain text (the default) or HTML.
.SH REFERENCES
Markham, N. R. and Zuker, M. (2008) UNAFold: software for nucleic acid folding and hybridization.  In Keith, J. M., editor, \fIBioinformatics, Volume II.  Structure, Functions and Applications\fR, number 453 in \fIMethods in Molecular Biology\fR, chapter 1, pages 3-31.  Humana Press, Totowa, NJ.  ISBN 978-1-60327-428-9.
.P
Other references which may be useful may be found at http://dinamelt.bioinfo.rpi.edu/refs.php.
.SH "SEE ALSO"
.BR ct-energy (1)
.SH AUTHORS
Nick Markham <markhn@rpi.edu> and Michael Zuker <zukerm@rpi.edu>
.SH COPYRIGHT
Copyright (c) 2006-2008, Rensselaer Polytechnic Institute.
.SH AVAILABILITY
UNAFold is available from http://dinamelt.bioinfo.rpi.edu/unafold/.  Commercial use requires a license; see http://dinamelt.bioinfo.rpi.edu/commercial.php.
