import os
version = os.environ['VERSION']
import yaml
import subprocess
import tomllib
with open(f"/opt/user/config.toml", "rb") as f:
    config = tomllib.load(f)


output_folder = "/opt/user/stats_and_variant_calling"
config_target_aa_annotation = config['prevalence_calling']['target_aa_annotation']
config_target_nt_annotation = config['prevalence_calling']['target_nt_annotation']
config_freebayes_settings = config['prevalence_calling']['freebayes_settings']
config_gene_id_to_genename = config['prevalence_calling']['geneid_to_genename']
config_aggregate_nucleotides = config['prevalence_calling']['aggregate_nucleotides']
config_aggregate_aminoacids = config['prevalence_calling']['aggregate_aminoacids']
config_annotate = config['prevalence_calling']['annotate']
config_decompose_options = config['prevalence_calling']['decompose_options']
config_annotated_vcf = config['prevalence_calling']['annotated_vcf']
config_aggregate_none = config['prevalence_calling']['aggregate_none']
config_output_prefix = config['prevalence_calling']['output_prefix']
config_min_site_qual = config['prevalence_calling']['min_site_qual']

freebayes_command_dict_yaml = open(output_folder + "/freebayes_command_dict.yaml", "r")
freebayes_command_dict = yaml.safe_load(freebayes_command_dict_yaml)

if config_target_aa_annotation:
	target_aa_annotation = "/opt/project_resources/"+config_target_aa_annotation
	target_nt_annotation = None
elif config_target_nt_annotation:
	target_aa_annotation = None
	target_nt_annotation = "/opt/project_resources/"+config_target_nt_annotation
else:
	target_aa_annotation = None
	target_nt_annotation = None

rule all:
	input:
		ref_table=output_folder + "/reference_AN_table.csv",
		cov_table=output_folder + "/coverage_AN_table.csv",
		alt_table=output_folder + "/alternate_AN_table.csv",



rule run_freebayes:
	"""
	Takes the contigs generated by the generate_contigs script and runs freebayes on them
	"""
	output:
		contig_vcf=output_folder + "/contig_vcfs/{contig}.vcf.gz",
	params:
		wdir=output_folder,
		freebayes_command_dict=freebayes_command_dict,
	# resources below are currently not utilized - haven't figured out a way to
	# get singularity profile, slurm profile, and high ulimits all at once.
	resources:
		mem_mb=200000,
		nodes=16,
		time_min=5760,
		#log_dir=log_folder
	script:
		"scripts/run_freebayes.py"


rule concatenate_and_fix_vcf_headers:
	input:
		contig_vcf=expand(
			output_folder + "/contig_vcfs/{contig}.vcf.gz",
			contig=freebayes_command_dict.keys(),
		),
	output:
		variants=output_folder + "/variants.vcf.gz",
	params:
		freebayes_settings=config_freebayes_settings,
		wdir=output_folder,
		settings_file="settings.txt",
	# resources below are currently not utilized - haven't figured out a way to
	# get singularity profile, slurm profile, and high ulimits all at once.
	resources:
		mem_mb=200000,
		nodes=16,
		time_min=5760,
		#log_dir=log_folder
	script:
		"scripts/concatenate_headers.py"

rule compress_vcf:
	'''
	compresses vcf file to be mutations only to avoid memory issues in next step
	'''
	input:
		original_vcf = output_folder + "/variants.vcf.gz"
	output:
		mutations_only_variants = output_folder + "/variants_mutations_only.vcf.gz",
	shell:
		"unpigz -c {input.original_vcf} | sed '/<\\*>/d' | pigz > {output.mutations_only_variants}"


rule generate_tables:
	input:
		variants = output_folder + "/variants_mutations_only.vcf.gz",
	output:
		ref_table=output_folder + "/reference_AN_table.csv",
		cov_table=output_folder + "/coverage_AN_table.csv",
		alt_table=output_folder + "/alternate_AN_table.csv",
	params:
		wdir=output_folder,
		settings_file="settings.txt",
		geneid_to_genename='/opt/project_resources/'+config_gene_id_to_genename,
		target_aa_annotation=target_aa_annotation,
		target_nt_annotation=target_nt_annotation,
		aggregate_nucleotides=config_aggregate_nucleotides,
		aggregate_aminoacids=config_aggregate_aminoacids,
		annotate=config_annotate,
		decompose_options=config_decompose_options,
		annotated_vcf=config_annotated_vcf,
		aggregate_none=config_aggregate_none,
		output_prefix=config_output_prefix,
		min_site_qual=config_min_site_qual
	script:
		"scripts/generate_tables.py"
