name: Notify Maintainers
on:
  schedule:
    - cron: 0 12 1,15 * *

  workflow_dispatch:

jobs:
  notify-maintainers:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v2

      - name: Notify maintainers
        run: |
          gh issue reopen ${{ env.ISSUE_NUMBER }}
          gh issue comment ${{ env.ISSUE_NUMBER }} -F .github/workflows/notify-message.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: 12
